import type { Video } from "./types";

/** 첫 실행 때 보여줄 예시 데이터 (localStorage 가 비어있을 때만 사용) */
export const SEED_VIDEOS: Video[] = [
  {
    id: "v1",
    title: "아침 루틴 30초",
    platform: "reels",
    ideaMemo: "기상 직후 컷 → 물 한 잔 클로즈업으로 시작. 따라하기 쉬운 3가지",
    stages: {
      idea: { status: "done" },
      script: { status: "done", note: "30초 분량 확정" },
      shoot: { status: "done" },
      edit: { status: "doing", note: "컷 편집 중" },
      caption: { status: "todo" },
      upload: { status: "todo" },
    },
    updatedAt: "2026-06-26",
  },
  {
    id: "v2",
    title: "위염에 좋은 식단 꿀팁",
    platform: "reels",
    ideaMemo: '"속 쓰릴 때 이거 드세요" 로 시작 → 양배추즙 3초 클로즈업',
    stages: {
      idea: { status: "done" },
      script: { status: "done", note: "35초 분량" },
      shoot: { status: "done", note: "3컷 다 찍음" },
      edit: { status: "blocked", note: "BGM 저작권 확인 필요" },
      caption: { status: "todo" },
      upload: { status: "todo" },
    },
    updatedAt: "2026-06-26",
  },
  {
    id: "v3",
    title: "브이로그 6월",
    platform: "youtube",
    ideaMemo: "한 달 정리 + 소소한 일상. 인트로에 6월 하이라이트 몽타주",
    stages: {
      idea: { status: "done" },
      script: { status: "done" },
      shoot: { status: "doing", note: "주말 추가 촬영 예정" },
      edit: { status: "todo" },
      caption: { status: "todo" },
      upload: { status: "todo" },
    },
    updatedAt: "2026-06-25",
  },
  {
    id: "v4",
    title: "저혈압인 사람 아침 운동",
    platform: "reels",
    ideaMemo: "어지럼 없이 천천히 깨우는 동작. 침대 위에서 가능한 버전",
    stages: {
      idea: { status: "doing" },
      script: { status: "todo" },
      shoot: { status: "todo" },
      edit: { status: "todo" },
      caption: { status: "todo" },
      upload: { status: "todo" },
    },
    updatedAt: "2026-06-24",
  },
  {
    id: "v5",
    title: "반신욕 ASMR",
    platform: "youtube",
    ideaMemo: "물소리 + 따뜻한 분위기. 잠 안 올 때 틀어두는 영상으로",
    stages: {
      idea: { status: "doing" },
      script: { status: "todo" },
      shoot: { status: "todo" },
      edit: { status: "todo" },
      caption: { status: "todo" },
      upload: { status: "todo" },
    },
    updatedAt: "2026-06-24",
  },
  {
    id: "v6",
    title: "5월 결산 회고",
    platform: "youtube",
    publishedDate: "2026-06-20",
    stages: {
      idea: { status: "done" },
      script: { status: "done" },
      shoot: { status: "done" },
      edit: { status: "done" },
      caption: { status: "done" },
      upload: { status: "done" },
    },
    metrics: { views: 12400, likes: 870, saves: 210, comments: 45 },
    updatedAt: "2026-06-20",
  },
];
